[dev]
	framework = "#custom"
	targetPort = 5173
	command = "npm run dev"

[build]
	base = ""
	command = "npm run build"
	publish = "dist"

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200

[build.environment]
	VITE_CYCLOPT_APPLICATION_GITHUB_URL = "https://github.com/apps/cyclopt-staging-app/installations/new"
	VITE_MAIN_SERVER_URL = "https://dev-server.cyclopt.services"
	VITE_REPORT_SERVICE_URL="https://dev-reports-service.cyclopt.services"
	VITE_SENTRY_ENVIRONMENT = "develop"

[context.production.environment]
	VITE_CYCLOPT_APPLICATION_GITHUB_URL = "https://github.com/apps/cyclopt/installations/new"
	VITE_MAIN_SERVER_URL = "https://server.cyclopt.services"
	VITE_REPORT_SERVICE_URL="https://reports-service.cyclopt.services"
	VITE_SENTRY_ENVIRONMENT = "production"
