[dev]
	framework = "#custom"
	targetPort = 5173
	command = "npm run dev"

[build]
	base = ""
	command = "npm run build"
	publish = "dist"

[[redirects]]
	from = "/*"
	to = "/index.html"
	status = 200

[build.environment]
	VITE_SERVER_URL = "https://dev-server.cyclopt.services"
	VITE_SENTRY_ENVIRONMENT = "develop"

[context.production.environment]
	VITE_SERVER_URL = "https://server.cyclopt.services"
	VITE_SENTRY_ENVIRONMENT = "production"
